### ISSUE TITLE
How to use your project

### ISSUE THREAD

**Issue by 1iverea9er** [straga/scrivo_project#2]
@straga 
Could you explain how to use your project to connect to AC.
I have to run the project on the installed Micropython ? 
Or is it necessary to compile the firmware first (how?) having configured everything beforehand (*.json, Wifi, board name, mqtt dev topic, hostname, mqtt)?

also I would like to understand is this a ready-made solution to use from HA or just for a test?

could you expand the sequence of steps a little for the layman.

And... what hardware mast i use for this? I hive ESP8266 and rs485<->Uart (TTL) converter
<img width="566" alt="image" src="https://user-images.githubusercontent.com/82063500/234334653-0d2afca8-772d-4504-be85-3890cc9cf311.png">

**Comment by 1iverea9er** [comment]
What topic listern your code when recive cmd?
I try this:
dev/ac_hisense_lr/ac_control/run_status
with payload: on
but ac not response

**Comment by straga** [comment]
What AC module you have. ? Open wait box.

**Comment by 1iverea9er** [comment]
Oh, I lost part of the way as it turned out. Sry
dev/ac_hisense_lr/cmd/ac_control/run_status

Now it works. The only thing AC does not take commands to name the temperature (even the ones on the list):
"temp_indoor_set":                      {"offset": 24,  "sz": 8, "prop": {"25": "00110011", "26": "00110101"}, "info": "you can send int or key, but need configure key"}
Do I have to do something extra for this?

**Comment by straga** [comment]
mqtt topic :
<img width="312" alt="image" src="https://github.com/straga/scrivo_project/assets/34532/db42bb46-0e3d-46ac-b099-44eda11950c8">

Send string value over MQTT. 
            elif msg.key == "temp_in":
                temperature = int(msg.payload.split('.')[0])
                self.cmd("101_0", {"temp_indoor_set": temperature})

**Comment by 1iverea9er** [comment]
Great work, @straga !!! It works! Thank you!!
Now I can send almost all commands provided by the remote control.
![image](https://github.com/straga/scrivo_project/assets/82063500/fe5bf2ad-9010-4058-a147-8ee34fc93715)
Are the "I feel" and "economy" commands provided?

**Comment by 1iverea9er** [comment]
Hi, @straga !
Could you explain how to get the "offset", "sz" and "value" parameters for all commands sent to AC:
<img width="409" alt="image" src="https://github.com/straga/scrivo_project/assets/82063500/45ec43d1-d026-4904-84d4-61af2189c5a0">
Judging by [these](https://github.com/htqwe22/device/blob/dev/src/protocol/air-condition_msg.c) and [these](https://github.com/htqwe22/device/blob/dev/src/protocol/air-condition_msg.h) files, the list of commands is much wider.

I am very interested in the temperature compensation function in the "dry" mode. My remote allows you to change the compensation value in the range of -7...+7C.

changing the "temp_indoor_set" parameter does not give anything, since apparently this parameter is located at a different address in bitarray and has different values

I am currently trying to get this data through reverse engineering using the hixe-va01a wall remote. However, I am not sure that it will be possible to connect it to my AC, because it is designed for VRF systems

**Comment by straga** [comment]
You need connect to Modbus wire, and check all message from Remote wall and AC. You can detect after push button or some change. Offset will be same or not, Files [these](https://github.com/htqwe22/device/blob/dev/src/protocol/air-condition_msg.c) and [these](https://github.com/htqwe22/device/blob/dev/src/protocol/air-condition_msg.h) will be like example, what may be.
Need a lot test.
What model AC and what Wifi module you have ?

**Comment by 1iverea9er** [comment]
My AC  -   AMS-09UR4SVEDB65 and i use WT32-ETH01 over LAN with ESPhome.
I know what data reporting AC when command sent by remote (DG11R2-01). But I do not know what to send via uart to get the same result. 

hex adress is [26]
hex offset is [10], start bit 80, how you know
`{"name": "temperature_compensation",         "offset": 80,  "sz": 5, "info": "13"},`
compensation 0 - hex 0x01
compensation +1 - hex 0x11
...
compensation +7 - hex 0x71
compensation -1 - hex 0x91
...
compensation -7 - hex 0xf1
<img width="379" alt="image" src="https://github.com/straga/scrivo_project/assets/82063500/51e3b500-250c-4a8a-9560-c2823ecc2386">

I haven't received the wall remote (hixe-va01a) yet. I tried experimentally to find the address and data to send, but AC does not respond

Did I understand you correctly that everything you managed to find out about "offset", "sz" and "value" was obtained exclusively by reverse engineering, but not by studying the protocol (that is, you cannot find out this data from the protocol) ? I'm asking because I'm not a programmer and it is very difficult for me to understand what is in the protocol code

**Comment by straga** [comment]
offset - from reversal and from protocol descriptions - just need to be analyzed. Protocol has different versions - you can ask AC which protocol and try to find descriptions of this version. But this is not in the public.

**Comment by straga** [comment]
new version upload. Try.

**Comment by 1iverea9er** [comment]
Thanks @straga . I still chose a solution based on ESPHome proposed by @pulsup2, modifying it to my needs.
